New fork changes
linuxserver/docker-cops pull request #43
Opened 2023-08-11 15:56 UTC by drizuid

undeprecate and update to new fork, remove arm32
please verify the jenkins crap

2023-08-11 16:05 UTC, nemchik requested changes
I didn't add duplicate comments to the arm64 dockerfile but it should all apply there too.

2023-08-11 16:05 UTC, nemchik commented on Dockerfile
> +# update to alpine 3.18 from archived linuxserver/docker-cops version
```suggestion
```
Comment isn't needed

2023-08-11 16:05 UTC, nemchik commented on Dockerfile
> +  # update to PHP 8.2 from archived linuxserver/docker-cops version
```suggestion
```
Comment isn't needed

2023-08-11 16:05 UTC, nemchik commented on Dockerfile
> +    php82-mbstring \
```suggestion
```
This is already included in the base https://github.com/linuxserver/docker-baseimage-alpine-nginx/blob/master/Dockerfile

2023-08-11 16:05 UTC, nemchik commented on Dockerfile
> +    # php82-json \
```suggestion
```
This is already included in the base https://github.com/linuxserver/docker-baseimage-alpine-nginx/blob/master/Dockerfile

2023-08-11 16:05 UTC, nemchik commented on Dockerfile
> +  # use standard composer 2.x now, no need to install older 1.x version
```suggestion
```

2023-08-11 16:05 UTC, nemchik commented on jenkins-vars.yml
>    - EXT_REPO = 'cops'
```suggestion
  - EXT_USER = 'mikespub-org'
  - EXT_REPO = 'seblucas-cops'
```

2023-08-11 16:15 UTC, drizuid commented
> I didn't add duplicate comments to the arm64 dockerfile but it should all apply there too.

Thanks!!

2023-08-11 23:27 UTC, nemchik commented on Dockerfile
> -# syntax=docker/dockerfile:1
This comment is needed

2023-08-11 23:28 UTC, nemchik commented on Dockerfile.aarch64
> -# syntax=docker/dockerfile:1
This comment is needed

2023-08-11 23:29 UTC, nemchik requested changes
Add back those two top line comments and this looks ready

2023-08-11 23:35 UTC, drizuid commented on Dockerfile
> -# syntax=docker/dockerfile:1
LOL i didnt mean to smoke that

2023-08-12 00:44 UTC, nemchik approved these changes

2023-08-12 02:16 UTC, merged