update config with note for full list of support configs
linuxserver/docker-cops pull request #48
Opened 2023-12-07 15:53 UTC by drizuid

closes https://github.com/linuxserver/docker-cops/issues/45

2023-12-07 17:20 UTC, mikespub commented
Hi @drizuid since this is a PHP file that will be included, and we want to avoid sending any *blank spaces* or *new lines* by mistake, could you please insert the comment *after* the first 3 lines:
```
<?php
    if (!isset($config))
        $config = array();

```
Thanks

2023-12-07 17:23 UTC, mikespub requested changes

2023-12-07 17:23 UTC, mikespub commented on root/defaults/config_local.php
> +
Oops, this is a newline - we just messed up any reply from the web server here :-)

Please move the comment *below* the <?php part as mentioned in the comment

2023-12-07 18:08 UTC, drizuid commented
oops, i should've caught that :D my bad. That is what i get for doing a PR from the phone!
LMK if this looks good now.

2023-12-08 22:00 UTC, mikespub commented
hi @drizuid you're good to go. For some reason Github won't let me approve my own review

2023-12-08 22:35 UTC, thelamer approved these changes

2023-12-09 01:34 UTC, merged